name: CI

on:
  push:
    branches: [main, "lab2/**"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  platform-ci:
    uses: GitFabien/platform-demo-lab1/.github/workflows/Zayonx-0/ci.yml@main
    permissions:
      contents: read
      packages: write
